version: '3.5'
services:
  src:
    build:
      context: src/
    volumes:
     - ./src:/app
     - /app/node_modules
    ports:
      - '3000:3000'
    links:
      - api
    depends_on:
      - api

  api:
    build:
      context: api/
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    environment:
     SEQ_DB: challenge
     SEQ_USER: postgres
     SEQ_PW: Yaotzin29416
     PORT: 5432
     #DATABASE_URL: 
      #- postgres://username:Yaotzin29416@db:5432/challenge
     NODE_CONFIG: '{"DATABASE_URL":"postgres://postgres:Yaotzin29416@db:5432/challenge"}'
  
  db: 
   image: postgres
   #env_file:
    #- database.env # configure postgres
   volumes:
    - ./src:/app
    - /app/node_modules
   ports:
    - '5432:5432'
   environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: challenge
    POSTGRES_PASSWORD: Yaotzin29416